export const styles = {
  layout: { display: "flex", height: "100vh", background: "#121212", fontFamily: "Segoe UI, sans-serif", position: "relative" },
  sidebar: { width: "200px", background: "#1e1e1e", borderRight: "1px solid #333", display: "flex", flexDirection: "column" },
  content: { flex: 1, padding: "30px", overflowY: "auto" },
  navBtn: (active) => ({
    padding: "20px", background: active ? "#3498db" : "transparent",
    color: active ? "white" : "#aaa", border: "none", textAlign: "left",
    cursor: "pointer", fontSize: "1.1em", fontWeight: "bold",
    borderBottom: "1px solid #333",
  }),
  panel: { background: "#1e1e1e", borderRadius: "8px", padding: "20px", marginBottom: "20px" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" },
  metricBig: { fontSize: "2em", fontWeight: "bold", color: "#000" },
  metricValue: { fontSize: "1.6em", fontWeight: "bold", color: "#000", textAlign: "center" },
  metricLabel: {
    color: "#000",
    fontSize: "0.9em",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    borderBottom: "1px solid #000",
    margin: "-14px -14px 14px -14px",
    padding: "8px 14px",
    background: "#fff",
    textAlign: "center",
    fontWeight: "bold"
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "14px",
    marginTop: "14px",
  },
  metricCard: {
    background: "#ffffff",
    border: "1px solid #000",
    borderRadius: "4px",
    padding: "14px",
    boxShadow: "none",
    minHeight: 150,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: "8px",
    overflow: "hidden",
    color: "#000"
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: "12px",
  },
  cardHint: { color: "#555", fontSize: "0.9em" },
  label: { color: "#aaa", fontSize: "0.75em", textTransform: "uppercase" },
  button: { padding: "10px 20px", background: "#3498db", border: "none", borderRadius: "4px", color: "white", cursor: "pointer", fontWeight: "bold", marginRight: "10px" },
  buttonDanger: { padding: "10px 20px", background: "#e74c3c", border: "none", borderRadius: "4px", color: "white", cursor: "pointer", fontWeight: "bold", marginRight: "10px" },
  buttonSecondary: { padding: "8px 14px", background: "#2c3e50", border: "none", borderRadius: "4px", color: "#ecf0f1", cursor: "pointer", fontWeight: "bold", marginRight: "8px", fontSize: "0.9em" },
  input: { background: "#000", border: "1px solid #555", color: "white", padding: "5px", width: "60px", textAlign: "center" },
  alarmOverlay: { position: "absolute", top: 0, left: 0, width: "100%", height: "100%", background: "rgba(192,57,43,0.9)", zIndex: 999, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" },
  disconnectOverlay: { position: "absolute", top: 0, left: 0, width: "100%", height: "100%", background: "rgba(0,0,0,0.8)", zIndex: 998, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" },
  statusBar: { position: "absolute", bottom: 0, left: 0, right: 0, background: "#111", borderTop: "1px solid #333", padding: "6px 16px", fontSize: "0.8em", display: "flex", justifyContent: "space-between", alignItems: "center", color: "#aaa" },
  row: { display: "flex", justifyContent: "space-between", padding: "5px 0", borderBottom: "1px solid #333" },
  manualBanner: { background: "#f39c12", color: "black", padding: "10px", fontWeight: "bold", marginBottom: "20px", borderRadius: "4px" },

  // DIP switch visualizer
  dipBlock: { background: "#c0392b", padding: "10px", borderRadius: 4, display: "inline-flex", gap: 5, border: "2px solid #fff" },
  dipLabel: { color: "white", fontSize: "0.7em", textAlign: "center", marginBottom: 2 },
  dipSwitch: { width: 20, height: 40, background: "#ecf0f1", position: "relative", borderRadius: 2 },
  dipKnob: (s) => ({
    width: 16, height: 16, background: "#2c3e50", position: "absolute",
    left: 2, top: s ? 22 : 2, transition: "top 0.2s", borderRadius: 2
  }),
  pill: {
    display: "inline-flex",
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: "999px",
    fontSize: "0.8em",
    fontWeight: "bold",
    letterSpacing: "0.5px",
    gap: "6px",
    background: "#1f2f3d",
    color: "#d7e0ea",
    border: "1px solid #2c3e50",
  },
  container: {
    maxWidth: "960px",
    margin: "0 auto",
  },
};
